global:
    scrape_interval: 15s
    evaluation_interval: 15s

    # Attach these labels to any time series or alerts when communicating with
    # external systems (federation, remote storage, Alertmanager).
    external_labels:
        monitor: "dapr-inventory-monitor"

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
#rule_files:
#- "alert.rules"

# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:
    # - job_name: "nodeexporter"
    #   scrape_interval: 5s
    #   static_configs:
    #       - targets: ["nodeexporter:9100"]

    # - job_name: "cadvisor"
    #   scrape_interval: 5s
    #   static_configs:
    #       - targets: ["cadvisor:8080"]
    - job_name: "dapr"
      scrape_interval: 5s
      static_configs:
          - targets: ["envoy-gateway:9090"]

    - job_name: "prometheus"
      scrape_interval: 10s
      static_configs:
          - targets: ["prometheus:9090", "localhost:9090"]

    - job_name: "pushgateway"
      scrape_interval: 10s
      honor_labels: true
      static_configs:
          - targets: ["pushgateway:9091"]
# remote_write:
#     - url: "<Your Prometheus remote_write endpoint>"
#       basic_auth:
#           username: "<Your Grafana Username>"
#           password: "<Your Grafana API key>"

#alerting:
# alertmanagers:
#     - scheme: http
#       static_configs:
#           - targets:
#                 - "alertmanager:9093"
#  - job_name: 'nginx'
#    scrape_interval: 10s
#    static_configs:
#      - targets: ['nginxexporter:9113']
