version: "3.4"

services:
    # seq is a log viewing tool
    seq:
        image: datalust/seq:latest
    redis-state-store:
        image: redis:alpine
    zipkin:
        image: openzipkin/zipkin-slim
        depends_on:
            - localstack # just make sure localstack is ready to go!
    rabbitmq:
        image: rabbitmq:3.10-management-alpine

    localstack:
        image: "localstack/localstack:0.14"

    dapr-actor-placement:
        image: "daprio/dapr:1.8.0"
        depends_on:
            - seq
            - zipkin
            - redis-state-store

    products-api-datastore-instance:
        image: amazon/dynamodb-local
        command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
    inventory-api-postgres:
        image: postgres:14-alpine
        restart: "no"

    products-api:
        image: ${REGISTRY:-daprinventory}/products.api:${TAG:-latest}
        build:
            context: ./packages/products-api
        restart: on-failure
        depends_on:
            - products-api-datastore-instance
            - zipkin
            - seq

    products-api-dapr: # dapr sidecar for products
        image: "daprio/daprd:1.8.0"
        restart: on-failure # important for local stack delays
        network_mode: "service:products-api" # this means it won't get it's own hostname and you can use the main service hostname like you would on k8s or whatever
        depends_on:
            - products-api
            - dapr-actor-placement
            - localstack

    inventory-api:
        image: ${REGISTRY:-daprinventory}/inventory.api:${TAG:-latest}
        restart: on-failure
        build:
            context: ./packages/inventory-api
        depends_on:
            - inventory-api-postgres
            - zipkin
            - seq

    inventory-api-dapr: # dapr sidecar for products
        image: "daprio/daprd:1.8.0"
        network_mode: "service:inventory-api"
        restart: on-failure # important for local stack delays
        depends_on:
            - inventory-api
            - dapr-actor-placement
            - localstack
