version: "3.4"
volumes:
    di-dynamo-data:

services:
    redis-state-store:
        # redis pass is not really a secret here
        command: redis-server --requirepass redispass
        ports:
            - "5379:6379"
    seq:
        environment:
            - ACCEPT_EULA=Y
        ports:
            - "5340:80"
    zipkin:
        ports:
            - "5411:9411"
    rabbitmq:
        ports:
            - "5672:5672"
    localstack:
        container_name: localstack
        ports:
            - "4566:4566" # LocalStack Gateway
            - "4510-4560:4510-4560" # exte
            # - "127.0.0.1:4566:4566" # LocalStack Gateway
            # - "127.0.0.1:4510-4560:4510-4560" # external services port range
        environment:
            - DEBUG=${DEBUG-}
            - PERSISTENCE=${PERSISTENCE-}
            - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR-}
            - DOCKER_HOST=unix:///var/run/docker.sock
            - EAGER_SERVICE_LOADING=0
            - DEBUG=1
        volumes:
            - "${LOCALSTACK_VOLUME_DIR:-./persist/.localstack}:/var/lib/localstack"
            - "/var/run/docker.sock:/var/run/docker.sock"

    inventory-api-postgres:
        ports:
            - 5413:5432
        volumes:
            - ./packages/inventory-api/infrastructure/database-initialisation:/docker-entrypoint-initdb.d
            - ./.docker-compose/.persist/inventory-api-postgres:/var/lib/postgresql/data
        environment:
            # these are for the local instance - not secret
            - POSTGRES_DB=InventoryDb
            - POSTGRES_SCHEMA_NAME=InventoryApi
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    dapr-actor-placement:
        command: ["./placement", "-port", "50000", "-log-level", "debug"]
        ports:
            - "50000:50000"

    products-api-datastore-instance:
        user: root # this fixes WARNING: [sqlite] cannot open DB[41]: com.almworks.sqlite4java.SQLiteException: [14] unable to open database file
        working_dir: /home/dynamodblocal
        volumes:
            - ./.docker-compose/.persist/product-api-dynamo-data:/home/dynamodblocal/data
        ports:
            - 5412:8000

    products-api:
        environment:
            - DAPR_SIDECAR_HOST=products-api
            - DAPR_SIDECAR_PORT=3500
            - DAPR_API_SECRET="some-secret"
            - OPEN_TELEMETRY_APP_NAME="products-api-app"
            - OPEN_TELEMETRY_ZIPKIN_URL=http://zipkin:9411/api/v2/spans
        ports:
            - "5101:80"
            - "3501:3500" # exposing dapr sidecar comms for testing
            - "50001:50001" # exposing dapr sidecar comms for testing

    products-api-dapr:
        command:
            [
                "./daprd",
                "-app-id",
                "products-api",
                "-app-port",
                "80",
                "-dapr-http-port",
                "3500",
                "-placement-host-address",
                "dapr-actor-placement:50000",
                "--enable-api-logging",
                "--log-level",
                "debug",
                "--log-as-json",
                "-components-path",
                "/dapr-meta/components",
                "-config",
                "/dapr-meta/configuration/main-config.yaml",
            ]
        volumes:
            - "./dapr:/dapr-meta"

    inventory-api:
        environment:
            - DAPR_SIDECAR_HOST=inventory-api
            - DAPR_SIDECAR_PORT=3500
            - DAPR_API_SECRET="some-secret"
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://0.0.0.0:80
            - OPEN_TELEMETRY_APP_NAME="inventory-api-app"
            - OPEN_TELEMETRY_ZIPKIN_URL=http://zipkin:9411/api/v2/spans
        ports:
            - "5102:80"
            - "3502:3500" # exposing dapr sidecar comms for testing
            - "50002:50001" # exposing dapr sidecar comms for testing
        volumes:
            - "./packages/inventory-api/Infrastructure/Migrations:/migrations"

    inventory-api-dapr:
        command:
            [
                "./daprd",
                "-app-id",
                "inventory-api",
                "-app-port",
                "80",
                "-dapr-http-port",
                "3500",
                "-placement-host-address",
                "dapr-actor-placement:50000",
                "--enable-api-logging",
                "--log-level",
                "debug",
                "--log-as-json",
                "-components-path",
                "/dapr-meta/components",
                "-config",
                "/dapr-meta/configuration/main-config.yaml",
            ]
        volumes:
            - "./dapr:/dapr-meta"
