version: "3.4"
volumes:
    di-dynamo-data:

services:
    redis-state-store:
        command: redis-server --requirepass redispass
        ports:
            - "5379:6379"
    seq:
        environment:
            - ACCEPT_EULA=Y
        ports:
            - "5340:80"
    zipkin:
        ports:
            - "5411:9411"

    inventory-api-postgres:
        ports:
            - 5413:5432
        volumes:
            - ./packages/inventory-api/database-initialisation:/docker-entrypoint-initdb.d
            - ./.docker-compose/.persist/inventory-api-postgres:/var/lib/postgresql/data
        environment:
            # these are for the local instance - not secret
            - POSTGRES_DB=InventoryDb
            - POSTGRES_SCHEMA_NAME=InventoryApi
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres

    dapr-actor-placement:
        command: ["./placement", "-port", "50000", "-log-level", "debug"]
        ports:
            - "50000:50000"
    products-api-dynamodb-instance:
        user: root # this fixes WARNING: [sqlite] cannot open DB[41]: com.almworks.sqlite4java.SQLiteException: [14] unable to open database file
        working_dir: /home/dynamodblocal
        volumes:
            - ./.docker-compose/.persist/product-api-dynamo-data:/home/dynamodblocal/data
        ports:
            - 5412:8000
    products-api:
        environment:
            - DAPR_SERVER_HOST=products-api
            - DAPR_SERVER_PORT=3001
            - DAPR_SIDECAR_HOST=products-api
            - DAPR_SIDECAR_PORT=3500
            - DAPR_API_SECRET="some-secret"
            - OPEN_TELEMETRY_APP_NAME="products-api"
            - OPEN_TELEMETRY_ZIPKIN_URL=http://zipkin:9411/api/v2/spans
        ports:
            - "5103:80"
            - "50001:50001" # for dapr sidecar comms

    products-api-dapr:
        command:
            [
                "./daprd",
                "-app-id",
                "products-api",
                "-app-port",
                "80",
                "-placement-host-address",
                "dapr-actor-placement:50000",
                "--enable-api-logging",
                "--log-as-json",
                "-components-path",
                "/dapr-meta/components",
                "-config",
                "/dapr-meta/configuration/main-config.yaml",
            ]
        volumes:
            - "./dapr:/dapr-meta"

    inventory-api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://0.0.0.0:80
            - RetryMigrations=true
            - SeqServerUrl=http://seq
            - OPEN_TELEMETRY_APP_NAME="inventory-api"
            - OPEN_TELEMETRY_ZIPKIN_URL=http://zipkin:9411/api/v2/spans
        ports:
            - "5104:80"
            - "50002:50001" # for dapr sidecar comms
        volumes:
            - "./packages/inventory-api/Infrastructure/Migrations:/migrations"

    inventory-api-dapr:
        command:
            [
                "./daprd",
                "-app-id",
                "inventory-api",
                "-app-port",
                "80",
                "-placement-host-address",
                "dapr-actor-placement:50000",
                "--enable-api-logging",
                "--log-as-json",
                "-components-path",
                "/dapr-meta/components",
                "-config",
                "/dapr-meta/configuration/main-config.yaml",
            ]
        volumes:
            - "./dapr:/dapr-meta"
