version: "3.4"
services:
    seq:
        environment:
            - ACCEPT_EULA=Y
        ports:
            - "5340:80"
    zipkin:
        ports:
            - "5411:9411"

    products-api:
        environment:
            - APP_TITLE=products-catalog
            - LOGGER_NAME=products-catalog
            - WEB_PORT=80
            - SEQ_URL=http://seq
            - NODE_ENV=dev # would use "production" on production
        ports:
            - "5103:80"
            - "50001:50001"

    products-api-dapr:
        command:
            [
                "./daprd",
                "-app-id",
                "products-api",
                "-app-port",
                "80",
                "-components-path",
                "/components",
                "-config",
                "/configuration/main-config.yaml",
            ]
        volumes:
            - "./dapr/components/:/components"
            - "./dapr/configuration/:/configuration"
