apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
    name: products-api-subscriptions
spec:
    topic: etl.inventory.availableProductInventory
    route: /products/awssdk/updatestock
    pubsubname: daprinventory-pubsub-sqs
scopes:
    - products-api
