apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
    name: products-api-subscriptions
spec:
    topic: etl.inventory.availableProductInventory
    route: /products/dapr/updatestock
    pubsubname: daprinventory-pubsub-rmq
scopes:
    - products-api
