apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
    name: daprinventory-pubsub-rmq
    namespace: daprinventory
spec:
    type: pubsub.rabbitmq
    version: v1
    metadata:
        - name: host
          value: "amqp://rabbitmq:5672"
        - name: durable
          value: "false"
        - name: deletedWhenUnused
          value: "false"
        - name: autoAck
          value: "false"
        - name: reconnectWait
          value: "0"
        - name: concurrency
          value: parallel
