apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
    name: daprinventory-secretstore
    namespace: daprinventory
spec:
    type: secretstores.local.file
    version: v1
    metadata:
        - name: multiValued
          value: true
        - name: secretsFile
          value: /dapr-meta/dapr-secrets-local.json
