apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
    name: daprinventory-statestore
    namespace: daprinventory
spec:
    type: state.redis
    version: v1
    metadata:
        - name: redisHost
          value: redis:6379
        - name: redisPassword
          secretKeyRef:
              name: stateStore.redisPassword
              key: stateStore.redisPassword
        - name: actorStateStore
          value: "true"
auth:
    secretStore: daprinventory-secretstore
