apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
    name: daprinventory-statestore
    namespace: daprinventory
spec:
    type: state.redis
    version: v1
    metadata:
        - name: redisHost
          value: redis-state-store:6379
        - name: redisPassword
          secretKeyRef:
              name: stateStore
              key: redisPassword
        - name: actorStateStore
          value: "true"
auth:
    secretStore: daprinventory-secretstore
