apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
    name: config
    namespace: daprinventory
spec:
    tracing:
        samplingRate: "1"
        zipkin:
            endpointAddress: "http://zipkin:9411/api/v2/spans"
