CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
SELECT 'CREATE DATABASE InventoryDb'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'InventoryDb');
CREATE SCHEMA IF NOT EXISTS InventoryApi AUTHORIZATION postgres;